// WebSetu — the marketing agent.
//
// Publishing a website is not the end of the work, and an owner who has just
// paid for one has no idea what to do next. This reads what the platform
// already knows — the quality report, the visitor and enquiry numbers, how much
// content exists, and which facts about the business are still missing — and
// turns it into a short, ordered list of things that would actually help, each
// one either done for them or pointed at the screen that does it.
//
// Nothing here is generated by a model, and nothing is invented about the
// business: every suggestion is a statement about the platform's own data
// ("42 visitors in the last fortnight, no enquiries"). That is also why it can
// be trusted to say the uncomfortable ones.

export interface SuggestionInput {
  /**
   * The stored report (or a fresh one). Only `issues[].fix` is read, and the
   * stored shape is the same one written by the checker, so the type is the
   * loose form the dashboard already has in hand.
   */
  quality?: { issues: { fix?: string }[] } | null;
  business: {
    phone?: string | null;
    whatsapp?: string | null;
    city?: string | null;
    address?: string | null;
    description?: string | null;
  };
  counts: {
    services: number;
    products: number;
    gallery: number;
    testimonials: number;
    faqs: number;
    blogPosts: number;
  };
  /** Last fortnight, from the platform's own analytics. */
  activity?: { visits: number; leads: number; ctaCalls: number; ctaWhatsapp: number };
  uniqueness?: number;
  /** The action the site was built to earn, so the advice fits the trade. */
  goal?: string | null;
}

export interface Suggestion {
  id: string;
  /** What to do, in one line. */
  title: string;
  /** Why it matters, from this business's own numbers. */
  why: string;
  impact: "high" | "medium" | "low";
  /**
   * "auto" is applied by the platform itself (structural fixes, the same ones
   * the quality checker marks), "owner" needs a fact only the business has.
   */
  kind: "auto" | "owner";
  /** Where to do it, when the owner has to. */
  tab?: "content" | "gallery" | "testimonials" | "faqs" | "blog" | "seo" | "business" | "builder";
}

const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

/**
 * The list, most valuable first.
 *
 * Ordering is by what the data says is costing the most: a business with traffic
 * and no enquiries is losing money every day, while a blog is a slow burn.
 */
export function suggestionsFor(input: SuggestionInput): Suggestion[] {
  const out: Suggestion[] = [];
  const c = input.counts;
  const activity = input.activity;
  const fixable = new Set((input.quality?.issues ?? []).map((i) => i.fix).filter(Boolean));

  // Traffic arriving and leaving without a word. This is the single most
  // valuable thing the platform can tell an owner, and it can only be said
  // because the analytics and the leads are in the same product.
  if (activity && activity.visits >= 15 && activity.leads === 0 && activity.ctaWhatsapp === 0 && activity.ctaCalls === 0) {
    out.push({
      id: "traffic-no-enquiries",
      title: "Turn the visitors you are already getting into enquiries",
      why: `${plural(activity.visits, "visitor")} in the last fortnight and not one enquiry or call. The page is being read and then abandoned.`,
      impact: "high",
      kind: fixable.size ? "auto" : "owner",
      tab: fixable.size ? undefined : "builder",
    });
  }

  if (!input.business.whatsapp) {
    out.push({
      id: "whatsapp",
      title: "Add a WhatsApp number",
      why: "Most buyers in this market message before they call, and the site has no WhatsApp button without a number to point at.",
      impact: "high",
      kind: "owner",
      tab: "business",
    });
  }

  if (c.services < 3) {
    out.push({
      id: "services",
      title: "List at least three services",
      why: `Only ${plural(c.services, "service")} on the site, so a visitor cannot tell what you actually do — and search has almost nothing to match.`,
      impact: "high",
      kind: "owner",
      tab: "content",
    });
  } else if (c.services < 6) {
    out.push({
      id: "services-more",
      title: "Add the rest of what you do",
      why: `${plural(c.services, "service")} listed. The trades that fill this page with six or eight get found for each of them separately.`,
      impact: "medium",
      kind: "owner",
      tab: "content",
    });
  }

  if (c.testimonials === 0) {
    out.push({
      id: "reviews",
      title: "Add two or three customer reviews",
      why: "There are none yet. On a local business page, reviews are the difference between a visitor calling you and calling the next shop.",
      impact: "high",
      kind: "owner",
      tab: "testimonials",
    });
  }

  if (c.gallery < 3) {
    out.push({
      id: "photos",
      title: "Add photos of your work",
      why: `Only ${plural(c.gallery, "photo")} in the gallery. Photos are the first thing visitors open and the second thing (after reviews) that makes them believe you.`,
      impact: "medium",
      kind: "owner",
      tab: "gallery",
    });
  }

  if (c.faqs < 4) {
    out.push({
      id: "faqs",
      title: "Answer the questions you get on the phone",
      why: `${plural(c.faqs, "question")} answered. Four to six is what search engines and AI assistants quote when someone asks about a business like yours.`,
      impact: "medium",
      kind: "owner",
      tab: "faqs",
    });
  }

  if (fixable.size) {
    out.push({
      id: "auto-fixes",
      title: `Let us fix ${plural(fixable.size, "issue")} on your site`,
      why: "These are structural — a section that is switched off, a missing About or contact block, the page title and description. We can do them now without asking you anything.",
      impact: "high",
      kind: "auto",
    });
  }

  if (typeof input.uniqueness === "number" && input.uniqueness < 55) {
    out.push({
      id: "uniqueness",
      title: "Give the design another draw",
      why: `This site is ${input.uniqueness}% distinct from the others in your trade — closer than we would like. A regenerate picks a different palette, type and layout.`,
      impact: "medium",
      kind: "owner",
      tab: "builder",
    });
  }

  if (c.blogPosts === 0) {
    out.push({
      id: "blog",
      title: "Write one article about what customers ask you",
      why: "There are no articles yet. One a month, answering a question you are asked in the shop, is what brings people in from search six months later.",
      impact: "low",
      kind: "owner",
      tab: "blog",
    });
  }

  if (!input.business.description) {
    out.push({
      id: "description",
      title: "Add a line about how you work",
      why: "The About section is running on filler because nothing was written about the business. Two sentences in your own words beat anything we can generate.",
      impact: "medium",
      kind: "owner",
      tab: "business",
    });
  }

  const rank = { high: 0, medium: 1, low: 2 };
  return out.sort((a, b) => rank[a.impact] - rank[b.impact]);
}

/** One line for the dashboard header: what the list adds up to. */
export function suggestionHeadline(list: Suggestion[]): string {
  const high = list.filter((s) => s.impact === "high").length;
  if (!list.length) return "Nothing needs your attention right now.";
  if (high >= 2) return `${high} things are costing you enquiries right now.`;
  return `${plural(list.length, "improvement")} worth making next.`;
}
