#!/usr/bin/env bash
#
# WebSetu — automatic nginx vhost + HTTPS certificate for customer domains.
#
# A customer adds their domain in the dashboard and points its DNS here. This
# script does the part that needs root: give that hostname an nginx server block
# pointing at the app, and get it a Let's Encrypt certificate.
#
# Run it once with --install (as root). After that a systemd timer runs it every
# few minutes and new customer domains come up on their own.
#
#   sudo bash server/auto-domains.sh --install
#   sudo bash server/auto-domains.sh            # one pass, by hand
#   sudo bash server/auto-domains.sh --list     # show what it manages
#   sudo bash server/auto-domains.sh --uninstall
#
# SAFETY — this is a shared server, so the rules are strict:
#   * It only ever writes, reads or deletes files named websetu-auto-*.conf.
#     Every other vhost, including CloudPanel's own and any site already on this
#     box, is never opened, never edited and never removed.
#   * It refuses to touch a hostname that another vhost already answers for, so
#     an existing site can never be hijacked by a customer typing its domain.
#   * nginx is only reloaded after `nginx -t` passes. A bad config is rolled
#     back, so a broken generated file cannot take the server down.
set -uo pipefail

APP_PORT="${APP_PORT:-4400}"
API_BASE="${API_BASE:-http://127.0.0.1:${APP_PORT}}"
TOKEN_FILE="${TOKEN_FILE:-/etc/websetu/internal-token}"
CONF_DIR="${CONF_DIR:-/etc/nginx/sites-enabled}"
PREFIX="websetu-auto-"
LE_EMAIL="${LE_EMAIL:-}"
LOG_TAG="websetu-domains"
WEBROOT="/var/www/websetu-acme"

log() { echo "[$(date '+%F %T')] $*"; logger -t "$LOG_TAG" -- "$*" 2>/dev/null || true; }
die() { log "ERROR: $*"; exit 1; }

[ "$(id -u)" = "0" ] || die "run as root (sudo bash $0 ...)"

# ---------------------------------------------------------------- install

install_self() {
  local src; src="$(readlink -f "$0")"
  install -D -m 755 "$src" /usr/local/sbin/websetu-auto-domains
  mkdir -p /etc/websetu "$WEBROOT/.well-known/acme-challenge"
  chown -R www-data:www-data "$WEBROOT" 2>/dev/null || true

  if [ ! -s "$TOKEN_FILE" ]; then
    die "missing $TOKEN_FILE. Put the same value as INTERNAL_TOKEN in the app's .env, then re-run --install"
  fi
  chmod 600 "$TOKEN_FILE"

  command -v certbot >/dev/null 2>&1 || {
    log "installing certbot"
    apt-get update -qq && apt-get install -y -qq certbot >/dev/null || die "could not install certbot"
  }

  cat >/etc/systemd/system/websetu-domains.service <<EOF
[Unit]
Description=WebSetu customer domain vhosts and certificates
After=network-online.target nginx.service

[Service]
Type=oneshot
Environment=APP_PORT=${APP_PORT}
Environment=LE_EMAIL=${LE_EMAIL}
ExecStart=/usr/local/sbin/websetu-auto-domains
EOF

  cat >/etc/systemd/system/websetu-domains.timer <<'EOF'
[Unit]
Description=Check for new WebSetu customer domains

[Timer]
OnBootSec=2min
OnUnitActiveSec=3min
AccuracySec=30s

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now websetu-domains.timer >/dev/null
  log "installed. Timer runs every 3 minutes."
  log "check it with: systemctl list-timers websetu-domains.timer"
}

uninstall_self() {
  systemctl disable --now websetu-domains.timer >/dev/null 2>&1 || true
  rm -f /etc/systemd/system/websetu-domains.{service,timer}
  systemctl daemon-reload
  log "timer removed. Generated vhosts were left in place; delete ${CONF_DIR}/${PREFIX}*.conf to remove them."
}

list_managed() {
  shopt -s nullglob
  local f found=0
  for f in "$CONF_DIR/$PREFIX"*.conf; do
    found=1
    echo "  $(basename "$f")"
  done
  [ "$found" = "1" ] || echo "  (none yet)"
}

# ----------------------------------------------------------------- helpers

# True when some OTHER vhost already claims this hostname. Protects every site
# that was on this server before, including the platform's own.
claimed_elsewhere() {
  local host="$1" hit
  hit="$(grep -rlE "^[[:space:]]*server_name[^;]*(^|[[:space:]])${host//./\\.}([[:space:]]|;)" \
        /etc/nginx/ 2>/dev/null | grep -v "/${PREFIX}" | head -1)"
  [ -n "$hit" ] && { log "skip ${host}: already served by $hit"; return 0; }
  return 1
}

write_vhost() {
  local host="$1" conf="$CONF_DIR/${PREFIX}${host}.conf"
  [ -f "$conf" ] && return 1
  cat >"$conf" <<EOF
# Generated by websetu-auto-domains for ${host}. Edited copies are overwritten.
server {
    listen 80;
    listen [::]:80;
    server_name ${host};

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT};
        default_type "text/plain";
    }

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
    }
}
EOF
  log "wrote vhost for ${host}"
  return 0
}

reload_nginx() {
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx && return 0
    log "nginx reload failed"
    return 1
  fi
  log "nginx config test FAILED — rolling back the files just written"
  return 1
}

issue_cert() {
  local host="$1"
  [ -d "/etc/letsencrypt/live/${host}" ] && return 0
  local args=(certonly --webroot -w "$WEBROOT" -d "$host"
              --non-interactive --agree-tos --keep-until-expiring)
  if [ -n "$LE_EMAIL" ]; then args+=(-m "$LE_EMAIL"); else args+=(--register-unsafely-without-email); fi
  if certbot "${args[@]}" >/dev/null 2>&1; then
    log "certificate issued for ${host}"
    return 0
  fi
  log "certificate NOT issued for ${host} (DNS may not point here yet; will retry)"
  return 1
}

# Add the TLS server block once the certificate exists.
add_tls() {
  local host="$1" conf="$CONF_DIR/${PREFIX}${host}.conf"
  grep -q "listen 443" "$conf" 2>/dev/null && return 1
  [ -d "/etc/letsencrypt/live/${host}" ] || return 1
  cat >>"$conf" <<EOF

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${host};

    ssl_certificate     /etc/letsencrypt/live/${host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${host}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
    }
}
EOF
  log "enabled HTTPS for ${host}"
  return 0
}

# --------------------------------------------------------------------- main

case "${1:-}" in
  --install)   install_self; exit 0 ;;
  --uninstall) uninstall_self; exit 0 ;;
  --list)      list_managed; exit 0 ;;
  "")          : ;;
  *)           die "unknown option $1" ;;
esac

[ -s "$TOKEN_FILE" ] || die "missing $TOKEN_FILE"
TOKEN="$(tr -d '\r\n' <"$TOKEN_FILE")"

response="$(curl -fsS --max-time 20 -H "x-internal-token: ${TOKEN}" "${API_BASE}/api/internal/domains" 2>/dev/null)" \
  || die "could not read the domain list from the app (is it running on ${API_BASE}?)"

# Hostname shape is enforced here as well as in the app: this value becomes a
# filename and an nginx directive, so nothing unexpected gets that far.
hostnames="$(printf '%s' "$response" \
  | grep -oE '"[A-Za-z0-9.-]+"' | tr -d '"' \
  | grep -E '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$' | sort -u)"

[ -n "$hostnames" ] || { log "no active customer domains"; exit 0; }

changed=0
for host in $hostnames; do
  claimed_elsewhere "$host" && continue
  if write_vhost "$host"; then changed=1; fi
done

if [ "$changed" = "1" ]; then
  reload_nginx || { shopt -s nullglob; for f in "$CONF_DIR/$PREFIX"*.conf; do nginx -t >/dev/null 2>&1 || rm -f "$f"; done; nginx -t >/dev/null 2>&1 && systemctl reload nginx; }
fi

changed=0
for host in $hostnames; do
  [ -f "$CONF_DIR/${PREFIX}${host}.conf" ] || continue
  issue_cert "$host" || continue
  if add_tls "$host"; then changed=1; fi
done
[ "$changed" = "1" ] && reload_nginx

# Domains removed in the dashboard stop being served, so their generated files go.
shopt -s nullglob
removed=0
for f in "$CONF_DIR/$PREFIX"*.conf; do
  base="$(basename "$f")"; host="${base#"$PREFIX"}"; host="${host%.conf}"
  printf '%s\n' $hostnames | grep -qx "$host" && continue
  rm -f "$f"; removed=1
  log "removed vhost for ${host} (no longer active in the dashboard)"
done
[ "$removed" = "1" ] && reload_nginx

exit 0
